name: platform-control-plane

services:
  platform-postgres:
    image: postgres:18.1-trixie
    container_name: platform-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform_db
    ports:
      - "15002:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - platform-postgres-data:/var/lib/postgresql

  platform-api:
    image: platform-api:latest
    container_name: platform-api
    restart: unless-stopped
    environment:
      RUST_LOG: info
      PLATFORM_API__APPLICATION__HOST: 0.0.0.0
      PLATFORM_API__APPLICATION__PORT: 8000
      PLATFORM_API__DATABASE__USERNAME: postgres
      PLATFORM_API__DATABASE__PASSWORD: postgres
      PLATFORM_API__DATABASE__PORT: 5432
      PLATFORM_API__DATABASE__HOST: host.docker.internal
      PLATFORM_API__DATABASE__NAME: platform_db
      PLATFORM_API__ORCHESTRATOR__ENDPOINT: "http://host.docker.internal:50051"
      PLATFORM_API__TRACING__ENABLED: false
      PLATFORM_API__TRACING__OTEL_EXPORTER_OTLP_ENDPOINT: ""
    ports:
      - "8000:8000"
    depends_on:
      platform-postgres:
        condition: service_healthy

volumes:
  platform-postgres-data:
