application:
  host: "0.0.0.0"
  port: 8000
database:
  username: "postgres"
  password: "postgres"
  port: 5432
  host: "localhost"
  database_name: "platform_db"
orchestrator:
  endpoint: "http://localhost:50051"