application:
  host: "0.0.0.0"
  port: 8000
database:
  username: "postgres"
  password: "postgres"
  port: 15002
  host: "localhost"
  name: "platform_db"
orchestrator:
  endpoint: "http://localhost:50051"
tracing:
  enabled: false
  otel_exporter_otlp_endpoint: ""